### ISSUE TITLE
 cannot find Key error

### ISSUE THREAD

**Issue by sravanikalikiri** [xdenser/node-struct#30]
Below is code which is leading error ,

var Struct = require('struct');
/*************************/
var Person = Struct()
    .chars('username',60)
    .chars('id',100);

Person.allocate();
Person.set('username',"sravani");
Person.set('id',"123456889994");

console.log("username: "+ Person.get('username') +"id:" +Person.get('sid'));

/**************/
[root@sravani nodejs]# node struct.js
home/wsadmin/src/sravani/nodejs/node_modules/struct/index.js:398
            throw new Error('Can not find field ' + key);
            ^

Error: Can not find field sid
    at Struct.get (/home/wsadmin/src/sravani/nodejs/node_modules/struct/index.js:398:19)
    at Object.<anonymous> (/home/wsadmin/src/sravani/nodejs/struct.js:11:65)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)

**Comment by sravanikalikiri** [comment]
Could you please provide more examples how to use this for a newbie

**Comment by sravanikalikiri** [comment]
It would be better if error shows which key is not matching
